#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bai_1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="quanlykh")]
	public partial class DBqlkhDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDichVu(DichVu instance);
    partial void UpdateDichVu(DichVu instance);
    partial void DeleteDichVu(DichVu instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertGiaoDich(GiaoDich instance);
    partial void UpdateGiaoDich(GiaoDich instance);
    partial void DeleteGiaoDich(GiaoDich instance);
    partial void InsertHopDong(HopDong instance);
    partial void UpdateHopDong(HopDong instance);
    partial void DeleteHopDong(HopDong instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLoaiDichVu(LoaiDichVu instance);
    partial void UpdateLoaiDichVu(LoaiDichVu instance);
    partial void DeleteLoaiDichVu(LoaiDichVu instance);
    partial void InsertLoaiKachHang(LoaiKachHang instance);
    partial void UpdateLoaiKachHang(LoaiKachHang instance);
    partial void DeleteLoaiKachHang(LoaiKachHang instance);
    #endregion
		
		public DBqlkhDataContext() : 
				base(global::QlkhNamespace.Properties.Settings.Default.quanlykhConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBqlkhDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBqlkhDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBqlkhDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBqlkhDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DichVu> DichVus
		{
			get
			{
				return this.GetTable<DichVu>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<GiaoDich> GiaoDiches
		{
			get
			{
				return this.GetTable<GiaoDich>();
			}
		}
		
		public System.Data.Linq.Table<HopDong> HopDongs
		{
			get
			{
				return this.GetTable<HopDong>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LoaiDichVu> LoaiDichVus
		{
			get
			{
				return this.GetTable<LoaiDichVu>();
			}
		}
		
		public System.Data.Linq.Table<LoaiKachHang> LoaiKachHangs
		{
			get
			{
				return this.GetTable<LoaiKachHang>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NhanVien_selectall")]
		public ISingleResult<NhanVien_selectallResult> NhanVien_selectall()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<NhanVien_selectallResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DichVu_selectall")]
		public ISingleResult<DichVu_selectallResult> DichVu_selectall()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<DichVu_selectallResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GiaoDich_selectall")]
		public ISingleResult<GiaoDich_selectallResult> GiaoDich_selectall()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GiaoDich_selectallResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HopDong_selectall")]
		public ISingleResult<HopDong_selectallResult> HopDong_selectall()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<HopDong_selectallResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KhachHang_selectall")]
		public ISingleResult<KhachHang_selectallResult> KhachHang_selectall()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<KhachHang_selectallResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LoaiDichVu_selectall")]
		public ISingleResult<LoaiDichVu_selectallResult> LoaiDichVu_selectall()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<LoaiDichVu_selectallResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LoaiKhachHang_selectall")]
		public ISingleResult<LoaiKhachHang_selectallResult> LoaiKhachHang_selectall()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<LoaiKhachHang_selectallResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DichVu")]
	public partial class DichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDV;
		
		private string _TenDV;
		
		private string _LoaiDV;
		
		private string _PhiDV;
		
		private string _Uudai;
		
		private string _Thongtinchitiet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDVChanging(string value);
    partial void OnMaDVChanged();
    partial void OnTenDVChanging(string value);
    partial void OnTenDVChanged();
    partial void OnLoaiDVChanging(string value);
    partial void OnLoaiDVChanged();
    partial void OnPhiDVChanging(string value);
    partial void OnPhiDVChanged();
    partial void OnUudaiChanging(string value);
    partial void OnUudaiChanged();
    partial void OnThongtinchitietChanging(string value);
    partial void OnThongtinchitietChanged();
    #endregion
		
		public DichVu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					this.OnMaDVChanging(value);
					this.SendPropertyChanging();
					this._MaDV = value;
					this.SendPropertyChanged("MaDV");
					this.OnMaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDV", DbType="NVarChar(300)")]
		public string TenDV
		{
			get
			{
				return this._TenDV;
			}
			set
			{
				if ((this._TenDV != value))
				{
					this.OnTenDVChanging(value);
					this.SendPropertyChanging();
					this._TenDV = value;
					this.SendPropertyChanged("TenDV");
					this.OnTenDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiDV", DbType="NVarChar(100)")]
		public string LoaiDV
		{
			get
			{
				return this._LoaiDV;
			}
			set
			{
				if ((this._LoaiDV != value))
				{
					this.OnLoaiDVChanging(value);
					this.SendPropertyChanging();
					this._LoaiDV = value;
					this.SendPropertyChanged("LoaiDV");
					this.OnLoaiDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiDV", DbType="VarChar(20)")]
		public string PhiDV
		{
			get
			{
				return this._PhiDV;
			}
			set
			{
				if ((this._PhiDV != value))
				{
					this.OnPhiDVChanging(value);
					this.SendPropertyChanging();
					this._PhiDV = value;
					this.SendPropertyChanged("PhiDV");
					this.OnPhiDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uudai", DbType="NVarChar(300)")]
		public string Uudai
		{
			get
			{
				return this._Uudai;
			}
			set
			{
				if ((this._Uudai != value))
				{
					this.OnUudaiChanging(value);
					this.SendPropertyChanging();
					this._Uudai = value;
					this.SendPropertyChanged("Uudai");
					this.OnUudaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thongtinchitiet", DbType="NVarChar(500)")]
		public string Thongtinchitiet
		{
			get
			{
				return this._Thongtinchitiet;
			}
			set
			{
				if ((this._Thongtinchitiet != value))
				{
					this.OnThongtinchitietChanging(value);
					this.SendPropertyChanging();
					this._Thongtinchitiet = value;
					this.SendPropertyChanged("Thongtinchitiet");
					this.OnThongtinchitietChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _Hoten;
		
		private string _SDT;
		
		private string _Email;
		
		private string _DiaChi;
		
		private string _ChucVu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    #endregion
		
		public NhanVien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(300)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(20)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(300)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(300)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(300)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiaoDich")]
	public partial class GiaoDich : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGD;
		
		private string _MaKH;
		
		private string _MaNV;
		
		private string _TenKH;
		
		private string _SoTK;
		
		private string _TenNN;
		
		private string _SoTKN;
		
		private string _NoiDung;
		
		private System.Nullable<System.DateTime> _NgayGD;
		
		private string _Phatsinhno;
		
		private string _Phatsingco;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGDChanging(string value);
    partial void OnMaGDChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnSoTKChanging(string value);
    partial void OnSoTKChanged();
    partial void OnTenNNChanging(string value);
    partial void OnTenNNChanged();
    partial void OnSoTKNChanging(string value);
    partial void OnSoTKNChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnNgayGDChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGDChanged();
    partial void OnPhatsinhnoChanging(string value);
    partial void OnPhatsinhnoChanged();
    partial void OnPhatsingcoChanging(string value);
    partial void OnPhatsingcoChanged();
    #endregion
		
		public GiaoDich()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGD", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGD
		{
			get
			{
				return this._MaGD;
			}
			set
			{
				if ((this._MaGD != value))
				{
					this.OnMaGDChanging(value);
					this.SendPropertyChanging();
					this._MaGD = value;
					this.SendPropertyChanged("MaGD");
					this.OnMaGDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="VarChar(20)")]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="VarChar(20)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(300)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTK", DbType="VarChar(20)")]
		public string SoTK
		{
			get
			{
				return this._SoTK;
			}
			set
			{
				if ((this._SoTK != value))
				{
					this.OnSoTKChanging(value);
					this.SendPropertyChanging();
					this._SoTK = value;
					this.SendPropertyChanged("SoTK");
					this.OnSoTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNN", DbType="NVarChar(300)")]
		public string TenNN
		{
			get
			{
				return this._TenNN;
			}
			set
			{
				if ((this._TenNN != value))
				{
					this.OnTenNNChanging(value);
					this.SendPropertyChanging();
					this._TenNN = value;
					this.SendPropertyChanged("TenNN");
					this.OnTenNNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTKN", DbType="VarChar(20)")]
		public string SoTKN
		{
			get
			{
				return this._SoTKN;
			}
			set
			{
				if ((this._SoTKN != value))
				{
					this.OnSoTKNChanging(value);
					this.SendPropertyChanging();
					this._SoTKN = value;
					this.SendPropertyChanged("SoTKN");
					this.OnSoTKNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(500)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGD", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayGD
		{
			get
			{
				return this._NgayGD;
			}
			set
			{
				if ((this._NgayGD != value))
				{
					this.OnNgayGDChanging(value);
					this.SendPropertyChanging();
					this._NgayGD = value;
					this.SendPropertyChanged("NgayGD");
					this.OnNgayGDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phatsinhno", DbType="VarChar(20)")]
		public string Phatsinhno
		{
			get
			{
				return this._Phatsinhno;
			}
			set
			{
				if ((this._Phatsinhno != value))
				{
					this.OnPhatsinhnoChanging(value);
					this.SendPropertyChanging();
					this._Phatsinhno = value;
					this.SendPropertyChanged("Phatsinhno");
					this.OnPhatsinhnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phatsingco", DbType="VarChar(20)")]
		public string Phatsingco
		{
			get
			{
				return this._Phatsingco;
			}
			set
			{
				if ((this._Phatsingco != value))
				{
					this.OnPhatsingcoChanging(value);
					this.SendPropertyChanging();
					this._Phatsingco = value;
					this.SendPropertyChanged("Phatsingco");
					this.OnPhatsingcoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HopDong")]
	public partial class HopDong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHD;
		
		private string _MaKH;
		
		private string _MaDV;
		
		private string _MaNV;
		
		private string _TenKH;
		
		private string _NguoiDD;
		
		private string _NoiDung;
		
		private string _GiaTri;
		
		private System.Nullable<System.DateTime> _NgayKy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(string value);
    partial void OnMaHDChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnMaDVChanging(string value);
    partial void OnMaDVChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnNguoiDDChanging(string value);
    partial void OnNguoiDDChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnGiaTriChanging(string value);
    partial void OnGiaTriChanged();
    partial void OnNgayKyChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKyChanged();
    #endregion
		
		public HopDong()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="VarChar(20)")]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="VarChar(20)")]
		public string MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					this.OnMaDVChanging(value);
					this.SendPropertyChanging();
					this._MaDV = value;
					this.SendPropertyChanged("MaDV");
					this.OnMaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="VarChar(20)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(300)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiDD", DbType="NVarChar(300)")]
		public string NguoiDD
		{
			get
			{
				return this._NguoiDD;
			}
			set
			{
				if ((this._NguoiDD != value))
				{
					this.OnNguoiDDChanging(value);
					this.SendPropertyChanging();
					this._NguoiDD = value;
					this.SendPropertyChanged("NguoiDD");
					this.OnNguoiDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(500)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTri", DbType="VarChar(20)")]
		public string GiaTri
		{
			get
			{
				return this._GiaTri;
			}
			set
			{
				if ((this._GiaTri != value))
				{
					this.OnGiaTriChanging(value);
					this.SendPropertyChanging();
					this._GiaTri = value;
					this.SendPropertyChanged("GiaTri");
					this.OnGiaTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKy", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayKy
		{
			get
			{
				return this._NgayKy;
			}
			set
			{
				if ((this._NgayKy != value))
				{
					this.OnNgayKyChanging(value);
					this.SendPropertyChanging();
					this._NgayKy = value;
					this.SendPropertyChanged("NgayKy");
					this.OnNgayKyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _TenKH;
		
		private string _LoaiKH;
		
		private string _LinhvucKD;
		
		private string _NguoiDD;
		
		private string _SoTK;
		
		private string _Sodu;
		
		private string _LoaiTien;
		
		private string _SDT;
		
		private string _Fax;
		
		private string _MaSoThue;
		
		private string _DiaChi;
		
		private string _Website;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnLoaiKHChanging(string value);
    partial void OnLoaiKHChanged();
    partial void OnLinhvucKDChanging(string value);
    partial void OnLinhvucKDChanged();
    partial void OnNguoiDDChanging(string value);
    partial void OnNguoiDDChanged();
    partial void OnSoTKChanging(string value);
    partial void OnSoTKChanged();
    partial void OnSoduChanging(string value);
    partial void OnSoduChanged();
    partial void OnLoaiTienChanging(string value);
    partial void OnLoaiTienChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnMaSoThueChanging(string value);
    partial void OnMaSoThueChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnWebsiteChanging(string value);
    partial void OnWebsiteChanged();
    #endregion
		
		public KhachHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(300)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiKH", DbType="NVarChar(100)")]
		public string LoaiKH
		{
			get
			{
				return this._LoaiKH;
			}
			set
			{
				if ((this._LoaiKH != value))
				{
					this.OnLoaiKHChanging(value);
					this.SendPropertyChanging();
					this._LoaiKH = value;
					this.SendPropertyChanged("LoaiKH");
					this.OnLoaiKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinhvucKD", DbType="NVarChar(300)")]
		public string LinhvucKD
		{
			get
			{
				return this._LinhvucKD;
			}
			set
			{
				if ((this._LinhvucKD != value))
				{
					this.OnLinhvucKDChanging(value);
					this.SendPropertyChanging();
					this._LinhvucKD = value;
					this.SendPropertyChanged("LinhvucKD");
					this.OnLinhvucKDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiDD", DbType="NVarChar(300)")]
		public string NguoiDD
		{
			get
			{
				return this._NguoiDD;
			}
			set
			{
				if ((this._NguoiDD != value))
				{
					this.OnNguoiDDChanging(value);
					this.SendPropertyChanging();
					this._NguoiDD = value;
					this.SendPropertyChanged("NguoiDD");
					this.OnNguoiDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTK", DbType="VarChar(20)")]
		public string SoTK
		{
			get
			{
				return this._SoTK;
			}
			set
			{
				if ((this._SoTK != value))
				{
					this.OnSoTKChanging(value);
					this.SendPropertyChanging();
					this._SoTK = value;
					this.SendPropertyChanged("SoTK");
					this.OnSoTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sodu", DbType="VarChar(20)")]
		public string Sodu
		{
			get
			{
				return this._Sodu;
			}
			set
			{
				if ((this._Sodu != value))
				{
					this.OnSoduChanging(value);
					this.SendPropertyChanging();
					this._Sodu = value;
					this.SendPropertyChanged("Sodu");
					this.OnSoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTien", DbType="NVarChar(100)")]
		public string LoaiTien
		{
			get
			{
				return this._LoaiTien;
			}
			set
			{
				if ((this._LoaiTien != value))
				{
					this.OnLoaiTienChanging(value);
					this.SendPropertyChanging();
					this._LoaiTien = value;
					this.SendPropertyChanged("LoaiTien");
					this.OnLoaiTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(20)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(20)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoThue", DbType="VarChar(20)")]
		public string MaSoThue
		{
			get
			{
				return this._MaSoThue;
			}
			set
			{
				if ((this._MaSoThue != value))
				{
					this.OnMaSoThueChanging(value);
					this.SendPropertyChanging();
					this._MaSoThue = value;
					this.SendPropertyChanged("MaSoThue");
					this.OnMaSoThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(300)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="VarChar(50)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this.OnWebsiteChanging(value);
					this.SendPropertyChanging();
					this._Website = value;
					this.SendPropertyChanged("Website");
					this.OnWebsiteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiDichVu")]
	public partial class LoaiDichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _LoaiDV;
		
		private string _Dacdiem;
		
		private string _Chinhsach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLoaiDVChanging(string value);
    partial void OnLoaiDVChanged();
    partial void OnDacdiemChanging(string value);
    partial void OnDacdiemChanged();
    partial void OnChinhsachChanging(string value);
    partial void OnChinhsachChanged();
    #endregion
		
		public LoaiDichVu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiDV", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LoaiDV
		{
			get
			{
				return this._LoaiDV;
			}
			set
			{
				if ((this._LoaiDV != value))
				{
					this.OnLoaiDVChanging(value);
					this.SendPropertyChanging();
					this._LoaiDV = value;
					this.SendPropertyChanged("LoaiDV");
					this.OnLoaiDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dacdiem", DbType="NVarChar(300)")]
		public string Dacdiem
		{
			get
			{
				return this._Dacdiem;
			}
			set
			{
				if ((this._Dacdiem != value))
				{
					this.OnDacdiemChanging(value);
					this.SendPropertyChanging();
					this._Dacdiem = value;
					this.SendPropertyChanged("Dacdiem");
					this.OnDacdiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chinhsach", DbType="NVarChar(300)")]
		public string Chinhsach
		{
			get
			{
				return this._Chinhsach;
			}
			set
			{
				if ((this._Chinhsach != value))
				{
					this.OnChinhsachChanging(value);
					this.SendPropertyChanging();
					this._Chinhsach = value;
					this.SendPropertyChanged("Chinhsach");
					this.OnChinhsachChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiKachHang")]
	public partial class LoaiKachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _LoaiKH;
		
		private string _Dacdiem;
		
		private string _Chinhsach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLoaiKHChanging(string value);
    partial void OnLoaiKHChanged();
    partial void OnDacdiemChanging(string value);
    partial void OnDacdiemChanged();
    partial void OnChinhsachChanging(string value);
    partial void OnChinhsachChanged();
    #endregion
		
		public LoaiKachHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiKH", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LoaiKH
		{
			get
			{
				return this._LoaiKH;
			}
			set
			{
				if ((this._LoaiKH != value))
				{
					this.OnLoaiKHChanging(value);
					this.SendPropertyChanging();
					this._LoaiKH = value;
					this.SendPropertyChanged("LoaiKH");
					this.OnLoaiKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dacdiem", DbType="NVarChar(300)")]
		public string Dacdiem
		{
			get
			{
				return this._Dacdiem;
			}
			set
			{
				if ((this._Dacdiem != value))
				{
					this.OnDacdiemChanging(value);
					this.SendPropertyChanging();
					this._Dacdiem = value;
					this.SendPropertyChanged("Dacdiem");
					this.OnDacdiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chinhsach", DbType="NVarChar(300)")]
		public string Chinhsach
		{
			get
			{
				return this._Chinhsach;
			}
			set
			{
				if ((this._Chinhsach != value))
				{
					this.OnChinhsachChanging(value);
					this.SendPropertyChanging();
					this._Chinhsach = value;
					this.SendPropertyChanged("Chinhsach");
					this.OnChinhsachChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class NhanVien_selectallResult
	{
		
		private string _MaNV;
		
		private string _Hoten;
		
		private string _SDT;
		
		private string _Email;
		
		private string _DiaChi;
		
		private string _ChucVu;
		
		public NhanVien_selectallResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this._MaNV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(300)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this._Hoten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(20)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this._SDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(300)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(300)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(300)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this._ChucVu = value;
				}
			}
		}
	}
	
	public partial class DichVu_selectallResult
	{
		
		private string _MaDV;
		
		private string _TenDV;
		
		private string _LoaiDV;
		
		private string _PhiDV;
		
		private string _Uudai;
		
		private string _Thongtinchitiet;
		
		public DichVu_selectallResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					this._MaDV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDV", DbType="NVarChar(300)")]
		public string TenDV
		{
			get
			{
				return this._TenDV;
			}
			set
			{
				if ((this._TenDV != value))
				{
					this._TenDV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiDV", DbType="NVarChar(100)")]
		public string LoaiDV
		{
			get
			{
				return this._LoaiDV;
			}
			set
			{
				if ((this._LoaiDV != value))
				{
					this._LoaiDV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiDV", DbType="VarChar(20)")]
		public string PhiDV
		{
			get
			{
				return this._PhiDV;
			}
			set
			{
				if ((this._PhiDV != value))
				{
					this._PhiDV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uudai", DbType="NVarChar(300)")]
		public string Uudai
		{
			get
			{
				return this._Uudai;
			}
			set
			{
				if ((this._Uudai != value))
				{
					this._Uudai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thongtinchitiet", DbType="NVarChar(500)")]
		public string Thongtinchitiet
		{
			get
			{
				return this._Thongtinchitiet;
			}
			set
			{
				if ((this._Thongtinchitiet != value))
				{
					this._Thongtinchitiet = value;
				}
			}
		}
	}
	
	public partial class GiaoDich_selectallResult
	{
		
		private string _MaGD;
		
		private string _MaKH;
		
		private string _MaDV;
		
		private string _MaNV;
		
		private string _TenKH;
		
		private string _SoTK;
		
		private string _TenNN;
		
		private string _SoTKN;
		
		private string _NoiDung;
		
		private System.Nullable<System.DateTime> _NgayGD;
		
		private string _Sotien;
		
		private string @__PhiDV;
		
		public GiaoDich_selectallResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGD", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaGD
		{
			get
			{
				return this._MaGD;
			}
			set
			{
				if ((this._MaGD != value))
				{
					this._MaGD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="VarChar(20)")]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this._MaKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="VarChar(20)")]
		public string MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					this._MaDV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="VarChar(20)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this._MaNV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(300)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this._TenKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTK", DbType="VarChar(20)")]
		public string SoTK
		{
			get
			{
				return this._SoTK;
			}
			set
			{
				if ((this._SoTK != value))
				{
					this._SoTK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNN", DbType="NVarChar(300)")]
		public string TenNN
		{
			get
			{
				return this._TenNN;
			}
			set
			{
				if ((this._TenNN != value))
				{
					this._TenNN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTKN", DbType="VarChar(20)")]
		public string SoTKN
		{
			get
			{
				return this._SoTKN;
			}
			set
			{
				if ((this._SoTKN != value))
				{
					this._SoTKN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(500)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this._NoiDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGD", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayGD
		{
			get
			{
				return this._NgayGD;
			}
			set
			{
				if ((this._NgayGD != value))
				{
					this._NgayGD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sotien", DbType="VarChar(20)")]
		public string Sotien
		{
			get
			{
				return this._Sotien;
			}
			set
			{
				if ((this._Sotien != value))
				{
					this._Sotien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ PhiDV]", Storage="__PhiDV", DbType="VarChar(20)")]
		public string _PhiDV
		{
			get
			{
				return this.@__PhiDV;
			}
			set
			{
				if ((this.@__PhiDV != value))
				{
					this.@__PhiDV = value;
				}
			}
		}
	}
	
	public partial class HopDong_selectallResult
	{
		
		private string _MaHD;
		
		private string _MaKH;
		
		private string _MaDV;
		
		private string _MaNV;
		
		private string _TenKH;
		
		private string _LoaiKH;
		
		private string _NguoiDD;
		
		private string _NoiDung;
		
		private string _PhiDV;
		
		private System.Nullable<System.DateTime> _NgayKy;
		
		public HopDong_selectallResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this._MaHD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="VarChar(20)")]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this._MaKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="VarChar(20)")]
		public string MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					this._MaDV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="VarChar(20)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this._MaNV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(300)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this._TenKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiKH", DbType="NVarChar(100)")]
		public string LoaiKH
		{
			get
			{
				return this._LoaiKH;
			}
			set
			{
				if ((this._LoaiKH != value))
				{
					this._LoaiKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiDD", DbType="NVarChar(300)")]
		public string NguoiDD
		{
			get
			{
				return this._NguoiDD;
			}
			set
			{
				if ((this._NguoiDD != value))
				{
					this._NguoiDD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(500)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this._NoiDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiDV", DbType="VarChar(20)")]
		public string PhiDV
		{
			get
			{
				return this._PhiDV;
			}
			set
			{
				if ((this._PhiDV != value))
				{
					this._PhiDV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKy", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayKy
		{
			get
			{
				return this._NgayKy;
			}
			set
			{
				if ((this._NgayKy != value))
				{
					this._NgayKy = value;
				}
			}
		}
	}
	
	public partial class KhachHang_selectallResult
	{
		
		private string _MaKH;
		
		private string _TenKH;
		
		private string _LoaiKH;
		
		private string _LinhvucKD;
		
		private string _NguoiDD;
		
		private string _SoTK;
		
		private string _Sodu;
		
		private string _LoaiTien;
		
		private string _SDT;
		
		private string _MaSoThue;
		
		private string _DiaChi;
		
		private string _Website;
		
		public KhachHang_selectallResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this._MaKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(300)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this._TenKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiKH", DbType="NVarChar(100)")]
		public string LoaiKH
		{
			get
			{
				return this._LoaiKH;
			}
			set
			{
				if ((this._LoaiKH != value))
				{
					this._LoaiKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinhvucKD", DbType="NVarChar(300)")]
		public string LinhvucKD
		{
			get
			{
				return this._LinhvucKD;
			}
			set
			{
				if ((this._LinhvucKD != value))
				{
					this._LinhvucKD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiDD", DbType="NVarChar(300)")]
		public string NguoiDD
		{
			get
			{
				return this._NguoiDD;
			}
			set
			{
				if ((this._NguoiDD != value))
				{
					this._NguoiDD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTK", DbType="VarChar(20)")]
		public string SoTK
		{
			get
			{
				return this._SoTK;
			}
			set
			{
				if ((this._SoTK != value))
				{
					this._SoTK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sodu", DbType="VarChar(20)")]
		public string Sodu
		{
			get
			{
				return this._Sodu;
			}
			set
			{
				if ((this._Sodu != value))
				{
					this._Sodu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTien", DbType="NVarChar(100)")]
		public string LoaiTien
		{
			get
			{
				return this._LoaiTien;
			}
			set
			{
				if ((this._LoaiTien != value))
				{
					this._LoaiTien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(20)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this._SDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoThue", DbType="VarChar(20)")]
		public string MaSoThue
		{
			get
			{
				return this._MaSoThue;
			}
			set
			{
				if ((this._MaSoThue != value))
				{
					this._MaSoThue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(300)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="VarChar(50)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this._Website = value;
				}
			}
		}
	}
	
	public partial class LoaiDichVu_selectallResult
	{
		
		private string _LoaiDV;
		
		private string _Dacdiem;
		
		private string _Chinhsach;
		
		public LoaiDichVu_selectallResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiDV", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string LoaiDV
		{
			get
			{
				return this._LoaiDV;
			}
			set
			{
				if ((this._LoaiDV != value))
				{
					this._LoaiDV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dacdiem", DbType="NVarChar(300)")]
		public string Dacdiem
		{
			get
			{
				return this._Dacdiem;
			}
			set
			{
				if ((this._Dacdiem != value))
				{
					this._Dacdiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chinhsach", DbType="NVarChar(300)")]
		public string Chinhsach
		{
			get
			{
				return this._Chinhsach;
			}
			set
			{
				if ((this._Chinhsach != value))
				{
					this._Chinhsach = value;
				}
			}
		}
	}
	
	public partial class LoaiKhachHang_selectallResult
	{
		
		private string _LoaiKH;
		
		private string _Dacdiem;
		
		private string _Chinhsach;
		
		public LoaiKhachHang_selectallResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiKH", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string LoaiKH
		{
			get
			{
				return this._LoaiKH;
			}
			set
			{
				if ((this._LoaiKH != value))
				{
					this._LoaiKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dacdiem", DbType="NVarChar(300)")]
		public string Dacdiem
		{
			get
			{
				return this._Dacdiem;
			}
			set
			{
				if ((this._Dacdiem != value))
				{
					this._Dacdiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chinhsach", DbType="NVarChar(300)")]
		public string Chinhsach
		{
			get
			{
				return this._Chinhsach;
			}
			set
			{
				if ((this._Chinhsach != value))
				{
					this._Chinhsach = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
