//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bai_1.DuLieu
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDich
    {
        public int MaGD { get; set; }
        public int MaKH { get; set; }
        public int MaNV { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayGD { get; set; }
        public Nullable<int> PhatSinhNo { get; set; }
        public Nullable<int> PhatSinhCo { get; set; }
        public string TenNguoiNhan { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
