//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bai_1.DuLieu
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        public int MaHD { get; set; }
        public int MaKH { get; set; }
        public int MaDV { get; set; }
        public Nullable<int> MaNV { get; set; }
        public string NoiDung { get; set; }
        public int GiaTri { get; set; }
        public System.DateTime NgayKy { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
