//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bai_1.DuLieu
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Forms;

    public partial class KhachHang
    {
        private ListViewItem itemselected;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.GiaoDiches = new HashSet<GiaoDich>();
            this.HopDongs = new HashSet<HopDong>();
        }

        public KhachHang(ListViewItem itemselected)
        {
            MaKH = Int32.Parse(itemselected.SubItems[0].Text);
            TenKH = itemselected.SubItems[1].Text;
            LoaiKH = itemselected.SubItems[2].Text;
            LinhVucKinhDoanh = itemselected.SubItems[3].Text;
            NguoiDaiDien = itemselected.SubItems[4].Text;
            DiaChi = itemselected.SubItems[5].Text;
            SDT = Int32.Parse(itemselected.SubItems[6].Text);
            Fax = Int32.Parse(itemselected.SubItems[7].Text);
            Website = itemselected.SubItems[8].Text;
            SoTaiKhoan = itemselected.SubItems[9].Text;
            SoDuKhaDung = Int32.Parse(itemselected.SubItems[10].Text);
            LoaiTien = itemselected.SubItems[11].Text;
            MaSoThue = itemselected.SubItems[12].Text;
        }

        public int MaKH { get; set; }
        public string TenKH { get; set; }
        public string LoaiKH { get; set; }
        public string LinhVucKinhDoanh { get; set; }
        public string NguoiDaiDien { get; set; }
        public string DiaChi { get; set; }
        public int SDT { get; set; }
        public int Fax { get; set; }
        public string Website { get; set; }
        public string SoTaiKhoan { get; set; }
        public int SoDuKhaDung { get; set; }
        public string LoaiTien { get; set; }
        public string MaSoThue { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDich> GiaoDiches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDong> HopDongs { get; set; }
    }
}
